#ifndef __CONFIG_H__
#define __CONFIG_H__

#define USE_INTERRUPT 1
#define USE_TIMER0 1
#define USE_TIMER1 1
#define TIMER0_16_MODE 1
#define TIMER1_16_MODE 1
#define TIMER0_COUNTER_MODE 0
#define TIMER1_COUNTER_MODE 0
#define TIMER0_H MS_50_H
#define TIMER0_L MS_50_L
#define TIMER1_H MS_25_H
#define TIMER1_L MS_25_L
#define DT_USE_FLOAT true
#define DT_USE_FLOAT_FAKE_APPROACH true
#define DS18B20_FREZZE_INTERRUPT true
#define DEBUG_DS18B20 false

#define TEMP_ALARM_WARNING_LEVEL 480    // 30.0C
#define TEMP_ALARM_ALARM_LEVEL 512      // 32.0C
#define TEMP_ALARM_DISMISS_DURATION 30  // 30s

#define KEY_USE_BUSY_WAITING true
#endif  // __CONFIG_H__